#!/usr/bin/env python3
"""
build-program-page.py -- generate the /program/ page (EN + ES).

Source content: the owner-provided design at
design/program-page-export.html (a real design-tool bundler export,
unlike the placeholder-free /service-areas/ and city pages, which have no
design source at all). Built by hand here rather than through
flatten-export.py's generic bundler resolver, matching how
build-city-pages.py and build-service-areas.py already work: a fixed,
well-understood page gets its own LABELS dict and new_tag() calls per
language, not a second generic template resolver.

Two facts on this page needed the owner's explicit confirmation before
being written at all -- see CLAUDE.md's "Proof" note and git history:
  - The Recent Work section names two real clients (Albany Pro Cleaning,
    Albany Junk Removal) with live links and screenshots. Only publish
    with their permission -- confirmed 2026-08.
  - "Only 5 businesses accepted per round" is a real operational cap the
    owner is committing to, not a placeholder number. If that cap ever
    changes, update PROGRAM_COPY here, not just this generated page.

Reuses the header and footer VERBATIM from the already-built homepage,
same as the city pages and the service-areas hub.

    python3 scripts/build-program-page.py [--out .]
"""

import argparse
import json
import pathlib
import sys
from html import escape

from bs4 import BeautifulSoup

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from build_lib import load_chrome, minify_css, rewrite_chrome_links  # noqa: E402

PROGRAM_PATH = {"en": "/program/", "es": "/es/program/"}

# Images already generated by scripts/optimize-images.mjs. logo-badge and
# program-badge are byte-identical to assets already used elsewhere on the
# site (verified by checksum) and reuse those existing derivatives; the
# other three are new to this page.
IMAGE_WIDTHS = {
    "program-badge": [320, 640],
    "proj-cleaning": [480, 640, 960],
    "proj-junk": [480, 640, 960],
    "program-hero-bg": [640, 960, 1280, 1659],
}
IMAGE_FALLBACK_EXT = {
    "program-badge": "png",
    "proj-cleaning": "jpg",
    "proj-junk": "jpg",
    "program-hero-bg": "jpg",
}
IMAGE_INTRINSIC = {
    "program-badge": (640, 427),
    "proj-cleaning": (960, 602),
    "proj-junk": (960, 667),
    "program-hero-bg": (1659, 948),
}


def picture_for(name, *, sizes, alt, hero=False, lazy=True, style=None, cls=None):
    widths = IMAGE_WIDTHS[name]
    ext = IMAGE_FALLBACK_EXT[name]
    w, h = IMAGE_INTRINSIC[name]
    avif = ", ".join(f"/assets/img/{name}-{x}.avif {x}w" for x in widths)
    webp = ", ".join(f"/assets/img/{name}-{x}.webp {x}w" for x in widths)

    attrs = [
        f'src="/assets/img/{name}-{widths[-1]}.{ext}"',
        f'alt="{escape(alt)}"',
        f'width="{w}"', f'height="{h}"',
        'decoding="async"',
    ]
    if hero:
        attrs.append('fetchpriority="high"')
    elif lazy:
        attrs.append('loading="lazy"')
    if style:
        attrs.append(f'style="{style}"')
    if cls:
        attrs.append(f'class="{cls}"')

    return (
        "<picture>"
        f'<source type="image/avif" srcset="{avif}" sizes="{sizes}">'
        f'<source type="image/webp" srcset="{webp}" sizes="{sizes}">'
        f'<img {" ".join(attrs)}>'
        "</picture>"
    )


LABELS = {
    "en": {
        "skip": "Skip to content",
        "eyebrow_hero": "The Willamette",
        "h1_line1": "30-DAY",
        "h1_line2": "PROGRAM",
        "tagline": "Launch Your Business. Build Your Future.",
        "lead": ("A focused 30-day program to build your online presence, "
                 "improve your visibility, and bring in more local "
                 "customers—website, local SEO, and Google Business, all "
                 "handled for you."),
        "apply_cta": "Apply for the 30-Day Program",
        "how_it_works": "See How It Works",
        "badge_alt": "The Willamette 30-Day Program badge",
        "badge_caption": ("We handle the strategy, setup, and "
                          "optimization—so you can focus on running your "
                          "business."),
        "badge_tagline": "Real results. No fluff.",
        "roadmap_heading": "The 30-Day Roadmap",
        "weeks": [
            {
                "label": "Week 1",
                "title": "Design & Launch",
                "body": ("We design your website and get it live—fast. "
                         "Your business goes online in the first week."),
            },
            {
                "label": "Week 2",
                "title": "Optimize & Verify",
                "body": ("We optimize your site, set up local SEO, verify "
                         "your Google Business Profile, and connect your "
                         "listings on Facebook, Instagram, Yelp, Apple "
                         "Business, Nextdoor, and Bing."),
            },
            {
                "label": "Week 3",
                "title": "Finalize & Grow",
                "body": ("We fine-tune everything, track performance, and "
                         "make sure your online presence is ready to "
                         "grow."),
            },
        ],
        "cap_prefix": "Only",
        "cap_number": "5",
        "cap_suffix": "businesses are accepted per round",
        "cap_body": ("We keep it limited so we can deliver real results "
                     "for every business."),
        "guarantee_heading": "30-Day Money-Back Guarantee",
        "guarantee_body": ("If you're not satisfied in the first 30 days, "
                           "we'll make it right."),
        "work_heading": "Recent Work",
        "work_lead": "Local Oregon businesses launched through the 30-Day Program.",
        "live": "Live",
        "stack": "Website · Local SEO · Google Business",
        "visit_site": "Visit Site",
        "final_eyebrow": "Now Accepting Applications",
        "final_heading": "Ready to Get Started?",
        "final_body": ("Apply for the 30-Day Program today. Spots are "
                       "limited to five businesses per round."),
        "final_cta": "Apply Now",
        "questions": "Questions? Call",
    },
    "es": {
        "skip": "Saltar al contenido",
        "eyebrow_hero": "El Programa",
        "h1_line1": "30 DÍAS",
        "h1_line2": "WILLAMETTE",
        "tagline": "Lanza Tu Negocio. Construye Tu Futuro.",
        "lead": ("Un programa enfocado de 30 días para construir tu "
                 "presencia en línea, mejorar tu visibilidad y atraer más "
                 "clientes locales — sitio web, SEO local y Google "
                 "Business, todo resuelto por nosotros."),
        "apply_cta": "Aplica al Programa de 30 Días",
        "how_it_works": "Ve Cómo Funciona",
        "badge_alt": "Insignia del Programa de 30 Días de Willamette",
        "badge_caption": ("Nosotros manejamos la estrategia, la "
                          "configuración y la optimización — para que tú "
                          "te enfoques en manejar tu negocio."),
        "badge_tagline": "Resultados reales. Sin relleno.",
        "roadmap_heading": "La Ruta de 30 Días",
        "weeks": [
            {
                "label": "Semana 1",
                "title": "Diseño y Lanzamiento",
                "body": ("Diseñamos tu sitio web y lo publicamos — "
                         "rápido. Tu negocio está en línea desde la "
                         "primera semana."),
            },
            {
                "label": "Semana 2",
                "title": "Optimización y Verificación",
                "body": ("Optimizamos tu sitio, configuramos el SEO "
                         "local, verificamos tu Perfil de Negocio de "
                         "Google y conectamos tus directorios en "
                         "Facebook, Instagram, Yelp, Apple Business, "
                         "Nextdoor y Bing."),
            },
            {
                "label": "Semana 3",
                "title": "Finaliza y Crece",
                "body": ("Afinamos todo, monitoreamos el rendimiento y "
                         "nos aseguramos de que tu presencia en línea "
                         "esté lista para crecer."),
            },
        ],
        "cap_prefix": "Solo",
        "cap_number": "5",
        "cap_suffix": "negocios son aceptados por ronda",
        "cap_body": ("Lo mantenemos limitado para poder dar resultados "
                     "reales a cada negocio."),
        "guarantee_heading": "Garantía de 30 Días con Devolución de Dinero",
        "guarantee_body": ("Si no estás satisfecho en los primeros 30 "
                           "días, lo resolvemos."),
        "work_heading": "Trabajos Recientes",
        "work_lead": "Negocios locales de Oregon lanzados a través del Programa de 30 Días.",
        "live": "En línea",
        "stack": "Sitio Web · SEO Local · Google Business",
        "visit_site": "Visitar Sitio",
        "final_eyebrow": "Aceptando Solicitudes",
        "final_heading": "¿Listo Para Empezar?",
        "final_body": ("Aplica al Programa de 30 Días hoy. Los espacios "
                       "están limitados a cinco negocios por ronda."),
        "final_cta": "Aplica Ahora",
        "questions": "¿Preguntas? Llama al",
    },
}

# Recent Work: real, permissioned case studies -- see the module docstring
# and CLAUDE.md's "Proof" note. Not translated (business names/descriptions
# are proper nouns / already short enough to read fine in either language),
# except the "Live" pill, stack line, and CTA which come from LABELS.
PROJECTS = [
    {
        "image": "proj-cleaning",
        "domain": "albanyprocleaning.com",
        "url": "https://albanyprocleaning.com",
        "name": "Albany Pro Cleaning",
        "en_desc": "Reliable, high-quality cleaning for homes and businesses in Albany, Oregon.",
        "es_desc": "Limpieza confiable y de alta calidad para casas y negocios en Albany, Oregon.",
        "alt": "Screenshot of the Albany Pro Cleaning website homepage",
    },
    {
        "image": "proj-junk",
        "domain": "albanyjunkremoval.org",
        "url": "https://albanyjunkremoval.org",
        "name": "Albany Junk Removal",
        "en_desc": "Fast, fully insured junk removal and cleanouts in Albany, Oregon and the Mid-Willamette Valley.",
        "es_desc": "Remoción de basura rápida y totalmente asegurada en Albany, Oregon y el valle medio de Willamette.",
        "alt": "Screenshot of the Albany Junk Removal website homepage",
    },
]


def check_icon_svg(color="var(--color-forest)"):
    return (f'<svg width="44" height="44" viewBox="0 0 48 48" fill="none" '
            f'stroke="{color}" stroke-width="1.9" stroke-linecap="round" '
            f'stroke-linejoin="round" style="flex-shrink:0">'
            f'<circle cx="18" cy="17" r="6"></circle>'
            f'<path d="M7 39c0-7 5-11 11-11s11 4 11 11"></path>'
            f'<circle cx="34" cy="19" r="4.5"></circle>'
            f'<path d="M31 30c6-1 11 3 11 9"></path></svg>')


def guarantee_icon_svg(color="var(--color-rust)"):
    return (f'<svg width="44" height="44" viewBox="0 0 48 48" fill="none" '
            f'stroke="{color}" stroke-width="1.9" stroke-linecap="round" '
            f'stroke-linejoin="round" style="flex-shrink:0">'
            f'<path d="M24 6 39 12v11c0 9-6 15-15 19C15 38 9 32 9 23V12l15-6Z">'
            f'</path><path d="m17 24 5 5 10-11"></path></svg>')


WEEK_ICONS = [
    ('<rect x="6" y="9" width="36" height="28" rx="2"></rect>'
     '<path d="M6 16h36M12 12.5h.1M17 12.5h.1M22 12.5h.1"></path>'
     '<path d="M13 23h13M13 28h21M13 33h16"></path>'),
    ('<circle cx="21" cy="21" r="12"></circle><path d="m30 30 10 10"></path>'
     '<path d="M21 17v8M17 21h8"></path>'),
    ('<path d="M8 39h32"></path>'
     '<path d="M12 34V24h6v10M22 34V17h6v17M32 34V10h6v24"></path>'
     '<path d="m10 19 9-7 8 4 11-9"></path>'),
]


def build_body(soup, lang, cfg):
    lab = LABELS[lang]
    home = "/" if lang == "en" else "/es/"
    apply_href = f"{home}#apply"

    main = soup.new_tag("main", id="main")

    # --- Hero ---
    hero = soup.new_tag("section", id="top", style=(
        "position:relative;overflow:hidden;min-height:min(72vh,620px);"
        "display:flex;flex-direction:column;justify-content:flex-end"))

    media = soup.new_tag("div", **{"class": "program-hero-media"})
    media.append(BeautifulSoup(
        picture_for("program-hero-bg", sizes="100vw", alt="", hero=True, lazy=False),
        "html.parser"))
    hero.append(media)

    hero_inner = soup.new_tag("div", style=(
        "position:relative;z-index:1;max-width:1200px;margin:0 auto;width:100%;"
        "box-sizing:border-box;padding:clamp(48px,7vw,88px) clamp(20px,5vw,64px)"))

    eyebrow = soup.new_tag("p", style=(
        "font:700 13px var(--font-ui);letter-spacing:.26em;text-transform:uppercase;"
        "color:var(--color-forest);opacity:.85;margin:0"))
    eyebrow.string = lab["eyebrow_hero"]

    h1 = soup.new_tag("h1", style=(
        "margin:12px 0 0;font:700 clamp(48px,7vw,84px)/.92 var(--font-display);"
        "letter-spacing:-.01em;color:var(--color-forest)"))
    h1.append(lab["h1_line1"])
    h1.append(soup.new_tag("br"))
    h1.append(lab["h1_line2"])

    tagline = soup.new_tag("p", style=(
        "margin:18px 0 0;font:700 22px var(--font-display);letter-spacing:.02em;"
        "line-height:1.25;color:var(--color-rust)"))
    tagline.string = lab["tagline"]

    lead = soup.new_tag("p", style=(
        "margin:18px 0 0;font:400 17px/1.6 var(--font-ui);color:var(--color-charcoal);"
        "max-width:46ch"))
    lead.string = lab["lead"]

    cta_row = soup.new_tag("div", style="margin-top:28px;display:flex;align-items:center;gap:20px;flex-wrap:wrap")
    apply_a = soup.new_tag("a", href=apply_href, **{"class": "btn btn--primary btn--lg"})
    apply_a.append(lab["apply_cta"] + " ")
    arw = soup.new_tag("span", **{"class": "arw", "aria-hidden": "true"})
    arw.string = "→"
    apply_a.append(arw)
    how_a = soup.new_tag("a", href="#roadmap", style=(
        "font:700 13px var(--font-ui);letter-spacing:.14em;text-transform:uppercase;"
        "color:var(--color-forest);text-decoration:none"))
    how_a.string = lab["how_it_works"] + " ↓"
    cta_row.append(apply_a)
    cta_row.append(how_a)

    hero_inner.append(eyebrow)
    hero_inner.append(h1)
    hero_inner.append(tagline)
    hero_inner.append(lead)
    hero_inner.append(cta_row)
    hero.append(hero_inner)
    main.append(hero)

    # --- Badge strip (below the hero, so it never overlaps the hero text on
    #     mobile -- see the earlier mobile-hero-overlap fix on the homepage) ---
    badge_section = soup.new_tag("section", style=(
        "padding:32px clamp(20px,5vw,64px) 0;max-width:1200px;margin:0 auto;"
        "display:flex;align-items:center;gap:24px;flex-wrap:wrap"))
    badge_pic = BeautifulSoup(
        picture_for("program-badge", sizes="140px", alt=lab["badge_alt"],
                    style="width:140px;height:auto;object-fit:contain"),
        "html.parser")
    badge_text = soup.new_tag("div")
    badge_caption = soup.new_tag("p", style="margin:0;font:400 15px/1.55 var(--font-ui);color:var(--color-charcoal);max-width:340px")
    badge_caption.string = lab["badge_caption"]
    badge_tagline = soup.new_tag("p", style="margin:8px 0 0;font:700 17px var(--font-display);color:var(--color-forest)")
    badge_tagline.string = lab["badge_tagline"]
    badge_text.append(badge_caption)
    badge_text.append(badge_tagline)
    badge_section.append(badge_pic)
    badge_section.append(badge_text)
    main.append(badge_section)

    # --- Roadmap ---
    roadmap = soup.new_tag("section", id="roadmap", style="max-width:1200px;margin:0 auto;padding:64px clamp(20px,5vw,64px) 24px")
    rm_head = soup.new_tag("div", style="display:flex;align-items:center;gap:20px")
    for _ in range(2):
        rule = soup.new_tag("div", style="flex:1;height:2px;background:var(--color-rust);opacity:.5")
        rm_head.append(rule)
    rm_h2 = soup.new_tag("h2", style="margin:0;font:700 28px var(--font-display);letter-spacing:.03em;text-transform:uppercase;color:var(--color-forest);text-align:center;white-space:nowrap")
    rm_h2.string = lab["roadmap_heading"]
    rm_head.insert(1, rm_h2)
    roadmap.append(rm_head)

    rm_grid = soup.new_tag("div", **{"data-reveal": "", "data-stagger": ""})
    rm_grid["style"] = "margin-top:44px;display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:40px"
    for week, icon_path in zip(lab["weeks"], WEEK_ICONS):
        col = soup.new_tag("div", **{"class": "lift"}, style="display:flex;flex-direction:column;align-items:center;text-align:center;padding:0 12px")
        circle = soup.new_tag("div", style="width:64px;height:64px;border-radius:50%;background:var(--color-forest);display:flex;align-items:center;justify-content:center")
        svg = BeautifulSoup(
            f'<svg width="30" height="30" viewBox="0 0 48 48" fill="none" stroke="var(--color-cream)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">{icon_path}</svg>',
            "html.parser")
        circle.append(svg)
        wk_label = soup.new_tag("div", style="margin-top:18px;font:700 13px var(--font-display);letter-spacing:.16em;text-transform:uppercase;color:var(--color-rust)")
        wk_label.string = week["label"]
        wk_title = soup.new_tag("div", style="margin-top:6px;font:700 21px var(--font-display);text-transform:uppercase;color:var(--color-forest)")
        wk_title.string = week["title"]
        wk_body = soup.new_tag("p", style="margin:10px 0 0;font:400 15px/1.6 var(--font-ui);color:var(--color-charcoal);max-width:300px")
        wk_body.string = week["body"]
        col.append(circle)
        col.append(wk_label)
        col.append(wk_title)
        col.append(wk_body)
        rm_grid.append(col)
    roadmap.append(rm_grid)
    main.append(roadmap)

    # --- Guarantee + cap ---
    guarantee = soup.new_tag("section", id="guarantee", style="max-width:1200px;margin:0 auto;padding:56px clamp(20px,5vw,64px)")
    g_grid = soup.new_tag("div", **{"data-reveal": ""}, style=(
        "display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:0;"
        "background:var(--color-cream-raised);border:1px solid var(--border-rule);"
        "border-radius:12px;overflow:hidden"))

    cap_cell = soup.new_tag("div", style="display:flex;align-items:center;gap:20px;padding:30px 34px")
    cap_cell.append(BeautifulSoup(check_icon_svg(), "html.parser"))
    cap_text = soup.new_tag("div")
    cap_heading = soup.new_tag("div", style="font:700 18px var(--font-display);letter-spacing:.03em;text-transform:uppercase;color:var(--color-forest);line-height:1.25")
    cap_heading.append(lab["cap_prefix"] + " ")
    cap_num = soup.new_tag("span", style="color:var(--color-rust);font-size:24px")
    cap_num.string = lab["cap_number"]
    cap_heading.append(cap_num)
    cap_heading.append(" " + lab["cap_suffix"])
    cap_body = soup.new_tag("p", style="margin:8px 0 0;font:400 14px/1.55 var(--font-ui);color:var(--color-charcoal)")
    cap_body.string = lab["cap_body"]
    cap_text.append(cap_heading)
    cap_text.append(cap_body)
    cap_cell.append(cap_text)

    guarantee_cell = soup.new_tag("div", style="display:flex;align-items:center;gap:20px;padding:30px 34px;border-left:1px solid var(--border-rule)")
    guarantee_cell.append(BeautifulSoup(guarantee_icon_svg(), "html.parser"))
    g_text = soup.new_tag("div")
    g_heading = soup.new_tag("div", style="font:700 18px var(--font-display);letter-spacing:.03em;text-transform:uppercase;color:var(--color-forest);line-height:1.25")
    g_heading.string = lab["guarantee_heading"]
    g_body = soup.new_tag("p", style="margin:8px 0 0;font:400 14px/1.55 var(--font-ui);color:var(--color-charcoal)")
    g_body.string = lab["guarantee_body"]
    g_text.append(g_heading)
    g_text.append(g_body)
    guarantee_cell.append(g_text)

    g_grid.append(cap_cell)
    g_grid.append(guarantee_cell)
    guarantee.append(g_grid)
    main.append(guarantee)

    # --- Recent Work ---
    work = soup.new_tag("section", id="work", style="background:var(--color-cream-deep)")
    work_inner = soup.new_tag("div", style="max-width:1200px;margin:0 auto;padding:64px clamp(20px,5vw,64px)")
    w_head = soup.new_tag("div", style="display:flex;align-items:center;gap:20px")
    for _ in range(2):
        rule = soup.new_tag("div", style="flex:1;height:2px;background:var(--color-rust);opacity:.5")
        w_head.append(rule)
    w_h2 = soup.new_tag("h2", style="margin:0;font:700 28px var(--font-display);letter-spacing:.03em;text-transform:uppercase;color:var(--color-forest);text-align:center;white-space:nowrap")
    w_h2.string = lab["work_heading"]
    w_head.insert(1, w_h2)
    work_inner.append(w_head)
    w_lead = soup.new_tag("p", style="margin:18px auto 0;max-width:560px;text-align:center;font:400 16px/1.6 var(--font-ui);color:var(--color-charcoal)")
    w_lead.string = lab["work_lead"]
    work_inner.append(w_lead)

    w_grid = soup.new_tag("div", **{"data-reveal": "", "data-stagger": ""}, style="margin-top:44px;display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:32px")
    for proj in PROJECTS:
        card = soup.new_tag("div", **{"class": "lift"}, style=(
            "background:var(--color-cream-raised);border:1px solid var(--border-rule);"
            "border-radius:12px;overflow:hidden;box-shadow:var(--shadow-card)"))
        chrome = soup.new_tag("div", style="background:var(--color-forest);padding:10px 16px;display:flex;align-items:center;gap:8px")
        for dot_color in ("var(--color-rust)", "var(--color-gold)", "var(--color-sage)"):
            dot = soup.new_tag("span", style=f"width:9px;height:9px;border-radius:50%;background:{dot_color}")
            chrome.append(dot)
        domain = soup.new_tag("span", style="margin-left:10px;font:400 12px var(--font-ui);color:var(--color-cream);opacity:.75")
        domain.string = proj["domain"]
        chrome.append(domain)
        card.append(chrome)

        img_wrap = soup.new_tag("div", style="position:relative;width:100%;aspect-ratio:16/10")
        img_wrap.append(BeautifulSoup(
            picture_for(proj["image"], sizes="(max-width:768px) 100vw, 480px",
                        alt=proj["alt"], style="width:100%;height:100%;object-fit:cover;display:block"),
            "html.parser"))
        card.append(img_wrap)

        body_wrap = soup.new_tag("div", style="padding:22px 24px 26px")
        pill = soup.new_tag("span", style=(
            "display:inline-block;font:700 11px var(--font-ui);letter-spacing:.12em;"
            "text-transform:uppercase;color:var(--color-forest);"
            "background:rgba(107,138,110,.2);border-radius:999px;padding:4px 11px"))
        pill.string = "● " + lab["live"]
        name = soup.new_tag("h3", style="margin:14px 0 0;font:700 23px var(--font-display);color:var(--color-forest)")
        name.string = proj["name"]
        desc = soup.new_tag("p", style="margin:6px 0 0;font:400 14.5px/1.55 var(--font-ui);color:var(--color-charcoal)")
        desc.string = proj["en_desc"] if lang == "en" else proj["es_desc"]
        meta_row = soup.new_tag("div", style="margin-top:14px;display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap")
        stack = soup.new_tag("div", style="font:700 10.5px var(--font-ui);letter-spacing:.1em;text-transform:uppercase;color:var(--color-forest);opacity:.75")
        stack.string = lab["stack"]
        visit = soup.new_tag("a", href=proj["url"], target="_blank", rel="noopener", style="font:700 12.5px var(--font-ui);letter-spacing:.06em;text-transform:uppercase;color:var(--color-rust);text-decoration:none")
        visit.string = lab["visit_site"] + " →"
        meta_row.append(stack)
        meta_row.append(visit)
        body_wrap.append(pill)
        body_wrap.append(name)
        body_wrap.append(desc)
        body_wrap.append(meta_row)
        card.append(body_wrap)
        w_grid.append(card)
    work_inner.append(w_grid)
    work.append(work_inner)
    main.append(work)

    # --- Final CTA ---
    final = soup.new_tag("section", style="background:var(--color-forest)")
    final_inner = soup.new_tag("div", style="max-width:1200px;margin:0 auto;padding:56px clamp(20px,5vw,64px);display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:36px")
    final_text = soup.new_tag("div", style="max-width:560px")
    final_eyebrow = soup.new_tag("div", style="font:700 13px var(--font-ui);letter-spacing:.22em;text-transform:uppercase;color:var(--color-rust)")
    final_eyebrow.string = lab["final_eyebrow"]
    final_h2 = soup.new_tag("h2", style="margin:12px 0 0;font:700 clamp(30px,4vw,42px)/1.05 var(--font-display);text-transform:uppercase;color:var(--color-cream)")
    final_h2.string = lab["final_heading"]
    final_body = soup.new_tag("p", style="margin:14px 0 0;font:400 16px/1.6 var(--font-ui);color:var(--color-cream);opacity:.86")
    final_body.string = lab["final_body"]
    final_text.append(final_eyebrow)
    final_text.append(final_h2)
    final_text.append(final_body)

    final_actions = soup.new_tag("div", style="display:flex;flex-direction:column;align-items:flex-start;gap:14px")
    final_a = soup.new_tag("a", href=apply_href, **{"class": "btn btn--primary btn--lg"})
    final_a.append(lab["final_cta"] + " ")
    arw2 = soup.new_tag("span", **{"class": "arw", "aria-hidden": "true"})
    arw2.string = "→"
    final_a.append(arw2)
    phone_line = soup.new_tag("div", style="font:400 14px var(--font-ui);color:var(--color-cream);opacity:.8")
    phone_line.append(lab["questions"] + " ")
    phone_a = soup.new_tag("a", href=cfg["nap"]["phoneHref"], style="color:var(--color-cream);font-weight:700")
    phone_a.string = cfg["nap"]["phoneDisplay"]
    phone_line.append(phone_a)
    final_actions.append(final_a)
    final_actions.append(phone_line)

    final_inner.append(final_text)
    final_inner.append(final_actions)
    final.append(final_inner)
    main.append(final)

    return main


def build_head(lang, cfg, css):
    origin = cfg["domain"]["origin"]
    nap = cfg["nap"]
    canonical = f"{origin}{PROGRAM_PATH[lang]}"
    alt_en = f"{origin}{PROGRAM_PATH['en']}"
    alt_es = f"{origin}{PROGRAM_PATH['es']}"
    og_image = f"{origin}/assets/img/og-image.png"
    ga4 = (cfg.get("analytics") or {}).get("ga4MeasurementId") or ""

    title = ("The Willamette 30-Day Program | Willamette Web Design" if lang == "en"
              else "El Programa de 30 Días de Willamette | Willamette Web Design")
    description = (
        "See exactly what happens each week of the 30-Day Program: website, "
        "local SEO, Google Business, and listings live in 30 days. $799, "
        "5 businesses per round."
        if lang == "en" else
        "Mira exactamente qué pasa cada semana del Programa de 30 Días: sitio "
        "web, SEO local, Google Business y directorios en línea en 30 días. "
        "$799, 5 negocios por ronda."
    )

    breadcrumb_items = [
        {"@type": "ListItem", "position": 1, "name": "Home" if lang == "en" else "Inicio",
         "item": f"{origin}/" if lang == "en" else f"{origin}/es/"},
        {"@type": "ListItem", "position": 2, "name": "Program" if lang == "en" else "Programa",
         "item": canonical},
    ]

    schema = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "WebPage",
                "@id": f"{canonical}#webpage",
                "url": canonical,
                "name": title,
                "inLanguage": "en-US" if lang == "en" else "es-US",
                "isPartOf": {"@id": f"{origin}/#website"},
                "about": {"@id": f"{origin}/#organization"},
                "breadcrumb": {"@id": f"{canonical}#breadcrumb"},
            },
            {
                "@type": "BreadcrumbList",
                "@id": f"{canonical}#breadcrumb",
                "itemListElement": breadcrumb_items,
            },
            {
                "@type": "Offer",
                "@id": f"{canonical}#offer",
                "name": "The Willamette 30-Day Program",
                "price": "799",
                "priceCurrency": "USD",
                "availability": "https://schema.org/InStock",
                "url": canonical,
                "seller": {"@id": f"{origin}/#organization"},
            },
        ],
    }

    hreflang = (
        f'<link rel="alternate" hreflang="en" href="{alt_en}">\n'
        f'<link rel="alternate" hreflang="es" href="{alt_es}">\n'
        f'<link rel="alternate" hreflang="x-default" href="{alt_en}">'
    )

    analytics = ""
    if ga4:
        analytics = f"""
<script>
(function(){{
  var ID='{ga4}';
  window.dataLayer=window.dataLayer||[];
  function gtag(){{dataLayer.push(arguments);}}
  window.gtag=gtag; gtag('js',new Date()); gtag('config',ID);
  var done=false;
  function load(){{
    if(done)return; done=true;
    var s=document.createElement('script');
    s.async=true; s.src='https://www.googletagmanager.com/gtag/js?id='+ID;
    document.head.appendChild(s);
  }}
  ['scroll','mousemove','touchstart','click','keydown'].forEach(function(e){{
    window.addEventListener(e,load,{{once:true,passive:true}});
  }});
  setTimeout(load,3000);
}})();
</script>"""

    preload = (
        '<link rel="preload" as="image" type="image/avif" '
        'href="/assets/img/program-hero-bg-640.avif" '
        'imagesrcset="/assets/img/program-hero-bg-640.avif 640w, '
        '/assets/img/program-hero-bg-960.avif 960w, '
        '/assets/img/program-hero-bg-1280.avif 1280w, '
        '/assets/img/program-hero-bg-1659.avif 1659w" '
        'imagesizes="100vw" fetchpriority="high">'
    )

    return f"""<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>{escape(title)}</title>
<meta name="description" content="{escape(description)}">
<link rel="canonical" href="{canonical}">
{hreflang}

<meta name="theme-color" content="#F3E7CE">
<meta name="geo.region" content="US-OR">

<meta property="og:type" content="website">
<meta property="og:site_name" content="{escape(cfg['brand']['name'])}">
<meta property="og:url" content="{canonical}">
<meta property="og:title" content="{escape(title)}">
<meta property="og:description" content="{escape(description)}">
<meta property="og:image" content="{og_image}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Willamette Web Design">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{escape(title)}">
<meta name="twitter:description" content="{escape(description)}">
<meta name="twitter:image" content="{og_image}">

<link rel="icon" href="/favicon.ico" sizes="16x16 32x32 48x48">
<link rel="icon" href="/assets/img/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/assets/img/apple-touch-icon.png">

<link rel="preload" as="font" type="font/woff2" href="/assets/fonts/inter-latin.woff2" crossorigin>
<link rel="preload" as="font" type="font/woff2" href="/assets/fonts/roboto-slab-latin.woff2" crossorigin>
{preload}

<script>document.documentElement.className+=' js';</script>

<style id="site-css">{css}</style>
<style id="page-css">
.program-hero-media {{ position:absolute; inset:0; z-index:0; }}
.program-hero-media img {{
  width:100%; height:100%; object-fit:cover; object-position:center bottom;
}}
.program-hero-media::after {{
  content:""; position:absolute; inset:0;
  background:linear-gradient(180deg, var(--color-cream) 0%, rgba(243,231,206,.55) 55%, rgba(243,231,206,.15) 100%);
}}
</style>
{analytics}
<script type="application/ld+json">{json.dumps(schema, ensure_ascii=False, separators=(",", ":"))}</script>"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=".")
    args = ap.parse_args()
    out_root = pathlib.Path(args.out)

    cfg = json.loads((out_root / "site.config.json").read_text())
    css_src = minify_css((out_root / "assets/css/site.css").read_text())

    for lang in ("en", "es"):
        lab = LABELS[lang]
        soup = BeautifulSoup("<!doctype html>", "html.parser")

        header_src, footer_src = load_chrome(out_root, lang)
        header = BeautifulSoup(str(header_src), "html.parser").find("header")
        footer = BeautifulSoup(str(footer_src), "html.parser").find("footer")
        urls = {"en": PROGRAM_PATH["en"], "es": PROGRAM_PATH["es"]}
        rewrite_chrome_links(header, lang, urls)
        rewrite_chrome_links(footer, lang, urls)

        body_main = build_body(soup, lang, cfg)

        html_str = (
            "<!doctype html>\n"
            f'<html lang="{lang}">\n<head>\n'
            + build_head(lang, cfg, css_src)
            + "\n</head>\n<body>\n"
            + f'<a class="skip" href="#main">{lab["skip"]}</a>\n'
            + str(header) + "\n"
            + str(body_main) + "\n"
            + str(footer) + "\n"
            + '<script src="/assets/js/site.js" defer></script>\n'
            + "</body>\n</html>\n"
        )

        dest = out_root / PROGRAM_PATH[lang].strip("/") / "index.html"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(html_str, encoding="utf-8")
        print(f"{lang}: {dest.relative_to(out_root)}  {len(html_str)/1024:.1f} KB")


if __name__ == "__main__":
    main()
