#!/usr/bin/env node
/**
 * build-sitemap.mjs — generates sitemap.xml from the pages that actually exist.
 *
 * Handbook §3.2 is explicit that <lastmod> must come from the build, not a
 * hardcoded date. This derives it from each file's last git commit (falling
 * back to filesystem mtime), so lastmod tells the truth about when the content
 * changed rather than when the sitemap was regenerated.
 *
 * It also refuses to list a page that is noindex or missing a canonical — a
 * sitemap that advertises non-indexable URLs wastes crawl budget and shows up
 * as an error in Search Console.
 *
 *   npm run sitemap
 *   node scripts/build-sitemap.mjs --dry   # print, don't write
 */

import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative, extname, dirname } from 'node:path';
import { execSync } from 'node:child_process';

const ROOT = process.cwd();
const CONFIG = JSON.parse(readFileSync(join(ROOT, 'site.config.json'), 'utf8'));
const ORIGIN = CONFIG.domain.origin.replace(/\/$/, '');
const DRY = process.argv.includes('--dry');

const SKIP_DIRS = new Set(['node_modules', '.git', '.netlify', 'reports', '_src', 'docs', '_templates', 'design']);
const SKIP_FILES = new Set(['404.html']);

/** Priority + changefreq by depth and page type. Rough, honest signals. */
function weight(urlPath) {
  if (urlPath === '/') return { priority: '1.0', changefreq: 'weekly' };
  const depth = urlPath.split('/').filter(Boolean).length;
  if (/^\/(services|pricing|contact)\/?$/.test(urlPath)) return { priority: '0.9', changefreq: 'monthly' };
  if (depth === 1) return { priority: '0.8', changefreq: 'monthly' };
  if (depth === 2) return { priority: '0.7', changefreq: 'monthly' };
  return { priority: '0.6', changefreq: 'yearly' };
}

function lastModified(absPath) {
  try {
    const out = execSync(`git log -1 --format=%cs -- "${relative(ROOT, absPath)}"`, {
      cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'],
    }).toString().trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(out)) return out;
  } catch { /* not committed yet, or not a git repo */ }
  return statSync(absPath).mtime.toISOString().slice(0, 10);
}

function walk(dir, acc = []) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry) || entry.startsWith('.')) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, acc);
    else if (extname(full) === '.html' && !SKIP_FILES.has(entry)) acc.push(full);
  }
  return acc;
}

/** /index.html -> "/",  /services/index.html -> "/services/" */
function toUrlPath(absPath) {
  const rel = relative(ROOT, absPath);
  if (rel === 'index.html') return '/';
  if (rel.endsWith('/index.html')) return `/${dirname(rel)}/`;
  return `/${rel}`;
}

const pages = walk(ROOT);
if (!pages.length) {
  console.log('No pages found yet — sitemap not generated.');
  console.log('This runs automatically once there are pages to list.');
  process.exit(0);
}

const entries = [];
const skipped = [];

for (const abs of pages) {
  const html = readFileSync(abs, 'utf8');
  const rel = relative(ROOT, abs);

  const robots = html.match(/<meta\b[^>]*name\s*=\s*["']robots["'][^>]*content\s*=\s*["']([^"']*)["']/i);
  if (robots && /noindex/i.test(robots[1])) {
    skipped.push([rel, 'noindex']);
    continue;
  }

  const canonical = html.match(/<link\b[^>]*rel\s*=\s*["']canonical["'][^>]*href\s*=\s*["']([^"']*)["']/i);
  if (!canonical) {
    skipped.push([rel, 'no canonical — cannot confirm the indexable URL']);
    continue;
  }

  // Trust the canonical over the file path: it is the URL Google will index.
  const loc = canonical[1];
  if (!loc.startsWith(ORIGIN)) {
    skipped.push([rel, `canonical is off-origin (${loc})`]);
    continue;
  }

  const urlPath = toUrlPath(abs);
  const { priority, changefreq } = weight(urlPath);
  entries.push({ loc, lastmod: lastModified(abs), changefreq, priority, rel });
}

entries.sort((a, b) => Number(b.priority) - Number(a.priority) || a.loc.localeCompare(b.loc));

// hreflang alternates, emitted only when the site is actually bilingual.
const bilingual = (CONFIG.languages || []).includes('es');
function alternates(loc) {
  if (!bilingual) return '';
  const path = loc.slice(ORIGIN.length);
  const en = path.startsWith('/es/') ? `${ORIGIN}${path.replace('/es/', '/')}` : loc;
  const es = path.startsWith('/es/') ? loc : `${ORIGIN}/es${path}`;
  return [
    `    <xhtml:link rel="alternate" hreflang="en" href="${en}"/>`,
    `    <xhtml:link rel="alternate" hreflang="es" href="${es}"/>`,
    `    <xhtml:link rel="alternate" hreflang="x-default" href="${en}"/>`,
  ].join('\n') + '\n';
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.mjs — do not edit by hand.
     lastmod comes from each page's last git commit, per handbook §3.2. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"${bilingual ? '\n        xmlns:xhtml="http://www.w3.org/1999/xhtml"' : ''}>
${entries.map((e) => `  <url>
    <loc>${e.loc}</loc>
${alternates(e.loc)}    <lastmod>${e.lastmod}</lastmod>
    <changefreq>${e.changefreq}</changefreq>
    <priority>${e.priority}</priority>
  </url>`).join('\n')}
</urlset>
`;

if (DRY) {
  console.log(xml);
} else {
  writeFileSync(join(ROOT, 'sitemap.xml'), xml);
  console.log(`\x1b[32m✔\x1b[0m sitemap.xml — ${entries.length} URL(s)`);
  entries.forEach((e) => console.log(`  ${e.priority}  ${e.lastmod}  ${e.loc}`));
}

if (skipped.length) {
  console.log(`\n\x1b[33mExcluded ${skipped.length} page(s):\x1b[0m`);
  skipped.forEach(([f, why]) => console.log(`  ${f} — ${why}`));
  console.log('\nA page missing from the sitemap will not be crawled reliably. Fix the reason, re-run.');
}
